[versions]
android-gradle = "8.12.1"
android-compileSdk = "36"
android-minSdk = "30"
android-targetSdk = "36"
androidx-activity = "1.10.1"
androidx-lifecycle = "2.9.2"
aboutlibraries = "12.2.4"
kotlin = "2.2.10"
composeHotReload = "1.0.0-beta05"
composeMultiplatform = "1.8.2"
detekt = "1.23.8"
java = "21"
kotlinx-coroutines = "1.10.2"
detekt-compose = "0.4.27"
versionCatalogLinter = "1.1.0"

[libraries]
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity" }
androidx-lifecycle-viewmodel = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
kotlinx-coroutinesSwing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
detekt-gradlePlugin = { group = "io.gitlab.arturbosch.detekt", name = "detekt-gradle-plugin", version.ref = "detekt" }
detekt-compose = { group = "io.nlopez.compose.rules", name = "detekt", version.ref = "detekt-compose" }
detekt-formatting = { group = "io.gitlab.arturbosch.detekt", name = "detekt-formatting", version.ref = "detekt" }
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "android-gradle" }
kotlin-compose-gradlePlugin = { group = "org.jetbrains.kotlin", name = "compose-compiler-gradle-plugin", version.ref = "kotlin" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
mupdf-kmp = { group = "com.sorrowblue.mupdf", name = "mupdf-kmp", version = "1.0.0" }
compose-gradlePlugin = { group = "org.jetbrains.compose", name = "org.jetbrains.compose.gradle.plugin", version.ref = "composeMultiplatform" }

[plugins]
aboutlibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutlibraries" }
comicviewer-lint = { id = "com.sorrowblue.comicviewer.plugin.lint" }
comicviewer-detekt = { id = "com.sorrowblue.comicviewer.plugin.detekt" }
comicviewer-gitTagVersion = { id = "com.sorrowblue.comicviewer.plugin.git-tag-version" }
versionCatalogLinter = { id = "io.github.pemistahl.version-catalog-linter", version.ref = "versionCatalogLinter" }
androidApplication = { id = "com.android.application", version.ref = "android-gradle" }
androidLibrary = { id = "com.android.library", version.ref = "android-gradle" }
composeHotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "composeHotReload" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
